# Generated by Django 4.2.13 on 2024-06-08 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('assunto', models.CharField(choices=[('Sugestão', 'Sugestão'), ('Reclamação', 'Reclamação'), ('Dúvida', 'Dúvida'), ('Outro', 'Outro')], max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(max_length=500, verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
