# Generated by Django 4.2.13 on 2024-06-07 20:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome da Área')),
                ('observacoes', models.TextField(verbose_name='Informações sobre a área')),
                ('codigo', models.CharField(editable=False, max_length=7, unique=True, verbose_name='Código da Área')),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Ideia')),
                ('descricao', models.TextField(verbose_name='Descrição da Ideia')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20, verbose_name='Status da Ideia')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('objetivos', models.TextField(blank=True, null=True, verbose_name='Objetivos')),
                ('metodologia', models.TextField(blank=True, null=True, verbose_name='Metodologia')),
                ('cronograma', models.TextField(blank=True, null=True, verbose_name='Cronograma')),
                ('tipo', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], default='Produto', max_length=20, verbose_name='Tipo')),
                ('problematica', models.TextField(blank=True, null=True, verbose_name='Problemática')),
                ('publico_alvo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Público Alvo')),
                ('viabilidade', models.TextField(blank=True, null=True, verbose_name='Análise de Viabilidade')),
                ('impacto', models.TextField(blank=True, null=True, verbose_name='Impacto Esperado')),
                ('investimento_desejado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Investimento Desejado (R$)')),
                ('resultados_esperados', models.TextField(blank=True, null=True, verbose_name='Resultados Esperados')),
                ('riscos', models.TextField(blank=True, null=True, verbose_name='Riscos e Mitigações')),
                ('parceiros', models.TextField(blank=True, null=True, verbose_name='Parcerias Estratégicas')),
                ('recursos_necessarios', models.TextField(blank=True, null=True, verbose_name='Recursos Necessários')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/%d/', verbose_name='Outros documentos')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='core.areas')),
            ],
            options={
                'verbose_name': 'Ideia',
                'verbose_name_plural': 'Ideias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Foto')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG')),
                ('orgao_expedidor', models.CharField(blank=True, choices=[('SSP', 'Secretaria de Segurança Pública'), ('PC', 'Polícia Civil'), ('DETRAN', 'Departamento de Trânsito'), ('ITEP', 'Instituto Técnico-Científico de Perícia'), ('POLITEC', 'Politec'), ('IGP', 'Instituto-Geral de Perícias'), ('IPC', 'Instituto de Polícia Científica')], max_length=20, null=True, verbose_name='Órgão Expedidor')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Rua/Avenida')),
                ('bairro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro')),
                ('numero', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=20, verbose_name='Nacionalidade')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data_de_inscricao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_proposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Proposta')),
                ('valor_investimento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Investimento (R$)')),
                ('condicoes', models.TextField(verbose_name='Condições da Proposta')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20, verbose_name='Status da Proposta')),
                ('retorno_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retorno Esperado (%)')),
                ('prazo_retorno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prazo para Retorno do Investimento')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários Adicionais')),
                ('ideia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ideia', verbose_name='Ideia')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Investidor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.AddField(
            model_name='ideia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideia', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('natureza_juridica', models.CharField(blank=True, max_length=70, null=True, verbose_name='Natureza Jurídica')),
                ('data_de_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura da Empresa')),
                ('situcao', models.CharField(choices=[('Nula', 'Nula'), ('Ativa', 'Ativa'), ('Suspensa', 'Suspensa'), ('Inapta', 'Inapta'), ('Ativa Não-Regular', 'Ativa Não-Regular'), ('Baixada', 'Baixada')], max_length=20, verbose_name='Situação Cadastral')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmar Dados')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Administrador da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
