# Generated by Django 4.2.13 on 2024-06-08 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Segmento', 'verbose_name_plural': 'Segmentos'},
        ),
        migrations.AddField(
            model_name='ideia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ideias/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Status do Usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
